# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            "sin9yt"
tagline:          "Home"
description:      "...the d4rk h4ck"
url:              "https://sin9yt.net"
baseurl:          /

author:
  name:           Sindhoor Tilak
  email:          sindhoor@sin9yt.net

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0

github:
  repo: "https://github.com/sin9yt/"
twitter: "https://twitter.com/sin9yt"
email: "sindhoor@sin9yt.net"
keybase: "https://keybase.io/sin9yt"
base: /